version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ticketgo
      - DB_SSLMODE=disable
      - PORT=8080
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - ticketgo-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ticketgo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ticketgo-network

volumes:
  postgres_data:

networks:
  ticketgo-network:
    driver: bridge 